name: Deploy to GKE
on:
  workflow_run:
    workflows:
    - "CI to Docker Hub"
    branches:
    - main
    types:
    - completed

jobs:
  deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Setup GCP Credentials'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Get GKE Credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: deel-challenge
        location: us-central1

    # Install helm
    - name: 'Install Helm'
      uses: azure/setup-helm@v3
      with:
        version: 'v3.10.2'
        token: ${{ secrets.GITHUB_TOKEN }}

    # Deploy sample image to the GKE cluster
    - name: Deploy
      run: |-
        helm dep build chart/reverse-ip;
        helm upgrade --install reverse-ip chart/reverse-ip \
          -f chart/reverse-ip/values.yaml \
          --atomic \
          --set image.tag=${{ github.sha }}
          --set mysql.auth.rootPassword=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          --set mysql.auth.password=${{ secrets.MYSQL_PASSWORD }}
