name: Deploy to GKE
on:
  workflow_run:
    workflows:
    - "CI to Docker Hub"
    branches:
    - main
    types:
    - completed

jobs:
  deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Authenticate against GCP
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials deel-challenge --region us-central1

    # Install helm
    - uses: azure/setup-helm@v3
      with:
        version: 'latest'
        token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      id: install

    # Deploy sample image to the GKE cluster
    - name: Deploy
      run: |-
        helm install reverse-ip chart/reverse-ip -f chart/reverse-ip/values.yaml --set image.tag=${{ github.sha }}
